### ISSUE TITLE
Failed Installation: Linksys WRT1900ACS

### ISSUE THREAD

**Issue by ghost** [black-roland/exOpenWrt#23]
Hey maintainers!

I was looking forward to setting up DNS crypt this weekend on my newish router and I ran into this:

Package dnscrypt-proxy-resolvers version 1.7.0-1.E-2016-08-01-22ff30b has no valid architecture, ignoring.
Package dnscrypt-proxy version 1.7.0-1.E has no valid architecture, ignoring.
Package hostip version 1.7.0-1.E has no valid architecture, ignoring.
Package iodine version 0.7.0-1.E has no valid architecture, ignoring.
Package iodined version 0.7.0-1.E has no valid architecture, ignoring.
Package libsodium version 1.0.11-1.E has no valid architecture, ignoring.

I just wanted to confirm that it may not be valid for the ARM chip on my linksys? 

I followed the instructions in the read me and even re-moved and re-added the alternative package repos. No luck.

**Comment by black-roland** [comment]
Hi.

> I just wanted to confirm that it may not be valid for the ARM chip on my linksys?

Yes, that's right. Your router based on Marvell Armada, not Atheros for which this repository is.

Since latest dnscrypt-proxy from this repository merged to upstream you can just install [stable LEDE firmware](https://downloads.lede-project.org/releases/17.01.0-rc2/targets/mvebu/generic/) or [OpenWrt DD from snapshots](https://wiki.openwrt.org/toh/linksys/wrt_ac_series#development) and you don't need exOpenWrt repository.
